import streamlit as st
import pandas as pd
import numpy as np


st.title('Data Summary')

'''
The data originally comes from the [National Institute of Health's National Library of Medicine](https://lhncbc.nlm.nih.gov/). It can be found via [TensorFlow](https://www.tensorflow.org/datasets/catalog/malaria) or [Kaggle](https://www.tensorflow.org/datasets/catalog/malaria). The data consists of 27,558 cell images with equal instances of parasitized and uninfected cells from the thin blood smear slide images of segmented cells. Having equal samples is important in the training of this model to avoid class bias in predictions generated by the model. 
'''

st.header('Example Data')
st.image('images/example_data.jpeg')

st.header('Auxiliary Data')
'''
I have also brought in auxiliary data that *is not* used in the modeling process. It's used to generate statistics and visualizations about malaria cases and deaths from around the world. This data is provided by the WHO and can be found in the following places: 
- [Estimated Cases](https://www.who.int/data/gho/data/indicators/indicator-details/GHO/estimated-number-of-malaria-cases)
- [Estimated Deaths](https://www.who.int/data/gho/data/indicators/indicator-details/GHO/estimated-number-of-malaria-deaths)
- [Confirmed Cases](https://www.who.int/data/gho/data/indicators/indicator-details/GHO/number-confirmed-malaria-cases)

(To access the data in CSV format, navigate to the data panel and right click the `EXPORT DATA in CSV format:` link and save link.)
'''
